### ISSUE TITLE
Prettier settings

### ISSUE THREAD

**Issue by 0xdabbad00** [GriddleGriddle/Griddle#84]
The settings view (where you can show/hide columns) is not pretty.  It ends up being a mess of checkboxes.

This is what I was able to make my settings look like:
![settings](https://cloud.githubusercontent.com/assets/1979334/6137836/6e1bdebc-b139-11e4-984a-766cd052c10c.png)

I made a bunch of css changes in order to pretty up my settings as shown in the above picture, where I added some text to say 'Show/hide columns', and instead of checkboxes, the column names are either displayed as normal text and underlined, or faded out.  The following css was used:

```css
/* Make buttons text */
.griddle button {
	border:none;
	background:none;
	margin:0 10px 0 0;
	font-weight: bold;
}

/* Get rid of blue box after clicking buttons */
.griddle button:focus {outline:0;}

/* Add text */
/* TODO: Use a component to add this text */
.griddle .griddle-settings .griddle-columns .griddle-column-selection:first-child:before {
	content: 'Show/hide columns:';
}

/* Don't display textbox */
.griddle .griddle-settings input[type=checkbox] {
  display: none;
}

/* Make column name faded out when "unchecked" */
.griddle .griddle-settings input[type=checkbox] + span {
	color: #aaa;
}

/* Make column name underlined when "checked" */
.griddle .griddle-settings input[type=checkbox]:checked + span {
	color: #000;
	text-decoration: underline;
}
```

I also added the cog icon next to the Settings text:
```javascript
var SettingsIconComponent = React.createElement("i", {className: "glyphicon glyphicon-cog"}, null);
```

Then when you declare your `Griddle` element you need to add the property `settingsIconComponent={SettingsIconComponent}`
